import type { Metadata } from "next";
import "./globals.css";
import { HeaderForDesktop, HeaderForMobile } from "@/components/Headers";
import { ThemeProvider } from "@/components/ThemeChanger/ThemeContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="transition-all duration-300 bg-gray-300 dark:bg-gray-700">
        <ThemeProvider>
          <HeaderForDesktop />
          {children}
          <HeaderForMobile />
        </ThemeProvider>
      </body>
    </html>
  );
}
